
#' srr standards: component plots
#'
#' @srrstats {G2.3} Univariate character inputs are validated according to
#' whether they are open identifiers or restricted choices. Restricted choices
#' include `na_action`, MASE scaling `method`, and the plotting `component`
#' selector. Open character inputs such as file paths, JMA `sea_area_id`,
#' labels, and URL-related strings are checked for type and length rather than
#' constrained to a fixed set of values.
#'
#' @srrstats {G2.3a} Restricted character choices use `match.arg()` or an
#' equivalent explicit membership check. `tempssm()` and
#' `.tempssm_prepare_model_inputs()` validate `na_action` with `match.arg()`.
#' `.compute_mase()` and `.scale_Q()` validate `method` with `match.arg()`.
#' `autoplot.tempssm()` validates `component` against the known component
#' names `level`, `drift`, `season`, and `ar1`.
#'
#' @srrstats {G2.3b} Restricted character choices are intentionally
#' case-sensitive. The package does not silently convert values with
#' `tolower()`, because accepted values are documented explicitly and invalid
#' or differently cased inputs should fail early. Unit tests cover invalid and
#' uppercase `na_action` values, invalid MASE scaling methods, and invalid
#' plotting component names.
#'
#' @srrstats {TS5.0} The package implements a default S3 `plot.tempssm()`
#' method for fitted `tempssm` objects. The method delegates to
#' `autoplot.tempssm()`, so `plot(res)` displays the same component plots as
#' `autoplot(res)` and accepts the same plotting arguments.
#'
#' @srrstats {TS5.1} Temporal plots label the horizontal axis as
#' `Time (year)`. Component plots generated by `autoplot_level()`,
#' `autoplot_drift()`, `autoplot_season()`, `autoplot_ar1()`,
#' `autoplot.tempssm()`, and `plot.tempssm()` map the continuous `time()`
#' index of the fitted `ts` series to the x-axis. `plot_temp_dev()` also
#' labels its horizontal axis as `Time (year)`. Unit tests check these axis
#' labels.
#'
#' @srrstats {TS5.2} Time is placed on the horizontal axis by default.
#' Component plots construct data frames with a `time` column derived from
#' `time(<ts>)` and map that column to the ggplot2 x aesthetic. The default
#' `plot.tempssm()` method delegates to `autoplot.tempssm()`, so the same
#' horizontal time-axis convention is used by both plotting interfaces.
#' `plot_temp_dev()` maps the anomaly time index to the horizontal axis,
#' with that axis labelled as `Time (year)`.
#'
#' @srrstats {TS5.3} Temporal plots print the time unit on the horizontal
#' axis by default. Component plots and `plot_temp_dev()` use
#' `Time (year)`, reflecting the continuous year scale returned by
#' `time(<ts>)` for the package's seasonal temperature time series.
#'
#' @noRd
NULL

#' Re-export the ggplot2 autoplot generic
#'
#' @importFrom ggplot2 autoplot
#' @export
ggplot2::autoplot


#' Validate requested component plots
#'
#' @param component Character vector of requested component names, or `NULL`.
#' @param choices Character vector of supported component names.
#'
#' @return A character vector containing one to four unique component names.
#' @noRd
.tempssm_autoplot_components <- function(component, choices) {
  if (is.null(component)) {
    return(choices)
  }

  valid <- is.character(component) &&
    length(component) >= 1L &&
    length(component) <= length(choices) &&
    !anyNA(component) &&
    !anyDuplicated(component) &&
    all(component %in% choices)
  if (!valid) {
    cli::cli_abort(c(
      "{.arg component} must contain one to four unique component names.",
      "i" = "Choose from: {toString(choices)}."
    ))
  }

  component
}


#' Resolve and validate a faceted component layout
#'
#' @param nrow,ncol Optional positive integers defining the facet layout.
#' @param n_components Number of selected components.
#'
#' @return A list containing `nrow` and `ncol`.
#' @noRd
.tempssm_facet_layout <- function(nrow, ncol, n_components) {
  validate_dimension <- function(x, arg_name) {
    if (is.null(x)) {
      return(invisible(NULL))
    }
    valid <- is.numeric(x) &&
      length(x) == 1L &&
      !is.na(x) &&
      is.finite(x) &&
      x >= 1 &&
      .tempssm_is_integerish(x)
    if (!valid) {
      cli::cli_abort("{.arg {arg_name}} must be a positive integer or NULL.")
    }
  }

  validate_dimension(nrow, "nrow")
  validate_dimension(ncol, "ncol")

  if (is.null(nrow) && is.null(ncol)) {
    dimensions <- switch(
      as.character(n_components),
      "1" = c(1L, 1L),
      "2" = c(1L, 2L),
      c(2L, 2L)
    )
    nrow <- dimensions[[1L]]
    ncol <- dimensions[[2L]]
  }

  if (!is.null(nrow) && !is.null(ncol) &&
      nrow * ncol < n_components) {
    cli::cli_abort(
      "{.arg nrow} * {.arg ncol} must accommodate all selected components."
    )
  }

  list(
    nrow = if (is.null(nrow)) NULL else as.integer(nrow),
    ncol = if (is.null(ncol)) NULL else as.integer(ncol)
  )
}


#' Combine component plots as one faceted ggplot
#'
#' @param plots Named list of component `ggplot` objects.
#' @inheritParams .tempssm_check_accessor_ci
#' @inheritParams .tempssm_facet_layout
#'
#' @return A faceted `ggplot` object.
#' @noRd
.tempssm_facet_component_plots <- function(plots, ci, nrow, ncol) {
  degree <- intToUtf8(176L)
  units <- c(
    level = paste0("(", degree, "C)"),
    drift = paste0("(", degree, "C/year)"),
    season = paste0("(", degree, "C)"),
    ar1 = paste0("(", degree, "C)")
  )
  titles <- vapply(plots, function(plot) plot$labels$title, character(1L))
  facet_labels <- paste(titles, units[names(plots)])

  plot_data <- Map(
    function(plot, component_name, facet_label) {
      data <- as.data.frame(plot$data)
      data$component_id <- component_name
      data$component <- factor(facet_label, levels = facet_labels)
      data$line_width <- if (component_name %in% c("level", "drift")) {
        1.2
      } else {
        0.5
      }
      data
    },
    plots,
    names(plots),
    facet_labels
  )
  combined_data <- do.call(rbind, plot_data)
  rownames(combined_data) <- NULL

  p <- ggplot2::ggplot(
    combined_data,
    ggplot2::aes(x = .data$time, y = .data$value)
  )
  if (ci) {
    p <- p + ggplot2::geom_ribbon(
      ggplot2::aes(ymin = .data$lwr, ymax = .data$upr),
      alpha = 0.3
    )
  }

  p +
    ggplot2::geom_line(
      ggplot2::aes(linewidth = .data$line_width),
      show.legend = FALSE
    ) +
    ggplot2::scale_linewidth_identity() +
    ggplot2::facet_wrap(
      ggplot2::vars(.data$component),
      scales = "free_y",
      nrow = nrow,
      ncol = ncol
    ) +
    ggplot2::scale_x_continuous(
      expand = ggplot2::expansion(mult = c(0.02, 0.04))
    ) +
    ggplot2::labs(x = "Time (year)", y = "Estimate")
}


#' Autoplot method for tempssm objects
#'
#' @description
#' Create diagnostic and component plots for a model fitted by
#' \code{tempssm()}. By default, all available components are plotted.
#'
#' @param object
#' An object returned by \code{tempssm()}.
#'
#' @param component
#' Character vector specifying one to four components to plot.
#' One of \code{"level"}, \code{"drift"}, \code{"season"}, or \code{"ar1"}.
#' Values must be unique and are displayed in the supplied order. If
#' \code{NULL} (default), all four components are plotted.
#'
#' @inheritParams get_level_ts
#'
#' @param nrow,ncol Optional positive integers specifying the facet layout when
#'   multiple components are plotted. When both are \code{NULL}, the layout is
#'   selected automatically; four components use a 2 by 2 layout. These
#'   arguments are ignored when one component is selected.
#'
#' @param ...
#' Additional arguments passed to the corresponding
#' \code{autoplot_*()} function.
#'
#' @return
#' A \code{ggplot} object. Multiple components are represented as facets with
#' free y-axis scales and component-specific units in the facet labels.
#'
#' @examples
#' \dontrun{
#' data(niigata_sst)
#' res <- tempssm(niigata_sst)
#'
#' # plot all components with 95% confidence interval
#' autoplot(res)
#'
#' # plot all components without 95% confidence interval
#' autoplot(res, ci = FALSE)
#'
#' # plot all components in one column
#' autoplot(res, nrow = 4, ncol = 1)
#'
#' # plot selected components in the supplied order
#' autoplot(res, component = c("drift", "level"))
#'
#' # plot one component
#' autoplot(res, component = "level", ci = FALSE)
#' }
#'
#' @method autoplot tempssm
#' @export
autoplot.tempssm <- function(object,
                             component = NULL,
                             ci = TRUE,
                             ci_level = 0.95,
                             nrow = NULL,
                             ncol = NULL,
                             ...) {

  plotters <- list(
    level  = autoplot_level,
    drift  = autoplot_drift,
    season = autoplot_season,
    ar1    = autoplot_ar1
  )

  components <- .tempssm_autoplot_components(
    component,
    names(plotters)
  )
  if (length(components) == 1L) {
    return(
      plotters[[components]](
        object,
        ci = ci,
        ci_level = ci_level,
        ...
      )
    )
  }

  layout <- .tempssm_facet_layout(nrow, ncol, length(components))
  plots <- lapply(
    plotters[components],
    function(f) f(object, ci = ci, ci_level = ci_level, ...)
  )

  .tempssm_facet_component_plots(
    plots,
    ci = ci,
    nrow = layout$nrow,
    ncol = layout$ncol
  )
}


#' Plot method for tempssm objects
#'
#' @description
#' Default base R plot method for objects fitted by \code{tempssm()}.
#' This method delegates to \code{autoplot.tempssm()} so that \code{plot(res)}
#' displays the same component plots as \code{autoplot(res)}.
#'
#' @param x An object returned by \code{tempssm()}.
#' @param ... Additional arguments passed to \code{autoplot.tempssm()}.
#'
#' @return
#' Invisibly returns the plotted \code{ggplot} object.
#'
#' @method plot tempssm
#' @export
#'
#' @examples
#' \dontrun{
#' data(niigata_sst)
#' res <- tempssm(niigata_sst)
#' plot(res)
#' plot(res, component = "level", ci = FALSE)
#' }
plot.tempssm <- function(x, ...) {
  p <- autoplot.tempssm(x, ...)
  print(p)
  invisible(p)
}
