
#' srr standards: component plots
#'
#' @srrstats {G2.3} Univariate character inputs are validated according to
#' whether they are open identifiers or restricted choices. Restricted choices
#' include `na_action`, MASE scaling `method`, and the plotting `component`
#' selector. Open character inputs such as file paths, JMA `sea_area_id`,
#' labels, and URL-related strings are checked for type and length rather than
#' constrained to a fixed set of values.
#'
#' @srrstats {G2.3a} Restricted character choices use `match.arg()` or an
#' equivalent explicit membership check. `tempssm()` and
#' `.tempssm_prepare_model_inputs()` validate `na_action` with `match.arg()`.
#' `.compute_mase()` and `.scale_Q()` validate `method` with `match.arg()`.
#' `autoplot.tempssm()` validates `component` against the known component
#' names `level`, `drift`, `season`, and `ar1`.
#'
#' @srrstats {G2.3b} Restricted character choices are intentionally
#' case-sensitive. The package does not silently convert values with
#' `tolower()`, because accepted values are documented explicitly and invalid
#' or differently cased inputs should fail early. Unit tests cover invalid and
#' uppercase `na_action` values, invalid MASE scaling methods, and invalid
#' plotting component names.
#'
#' @srrstats {TS5.0} The package implements a default S3 `plot.tempssm()`
#' method for fitted `tempssm` objects. The method delegates to
#' `autoplot.tempssm()`, so `plot(res)` displays the same component plots as
#' `autoplot(res)` and accepts the same plotting arguments.
#'
#' @srrstats {TS5.1} Temporal plots label the horizontal axis as
#' `Time (year)`. Component plots generated by `autoplot_level()`,
#' `autoplot_drift()`, `autoplot_season()`, `autoplot_ar1()`,
#' `autoplot.tempssm()`, and `plot.tempssm()` map the continuous `time()`
#' index of the fitted `ts` series to the x-axis. `plot_temp_dev()` also
#' labels its horizontal axis as `Time (year)`. Unit tests check these axis
#' labels.
#'
#' @srrstats {TS5.2} Time is placed on the horizontal axis by default.
#' Component plots construct data frames with a `time` column derived from
#' `time(<ts>)` and map that column to the ggplot2 x aesthetic. The default
#' `plot.tempssm()` method delegates to `autoplot.tempssm()`, so the same
#' horizontal time-axis convention is used by both plotting interfaces.
#' `plot_temp_dev()` maps the anomaly time index to the horizontal axis,
#' with that axis labelled as `Time (year)`.
#'
#' @srrstats {TS5.3} Temporal plots print the time unit on the horizontal
#' axis by default. Component plots and `plot_temp_dev()` use
#' `Time (year)`, reflecting the continuous year scale returned by
#' `time(<ts>)` for the package's seasonal temperature time series.
#'
#' @noRd
NULL

#' Arrange ggplot objects and return a gtable
#'
#' @param plots A list of ggplot objects
#' @param nrow Number of rows
#' @param ncol Number of columns
#'
#' @return A gtable object (grob)
#' @keywords internal
#' @noRd
.make_gtable_layout <- function(plots,
                               nrow = length(plots),
                               ncol = 1) {
  if (!is.list(plots)) {
    stop("`plots` must be a list.", call. = FALSE)
  }

  if (!is.numeric(nrow) ||
      length(nrow) != 1 ||
      !is.finite(nrow) ||
      nrow < 1 ||
      !.tempssm_is_integerish(nrow)) {
    stop("`nrow` must be a positive integer.", call. = FALSE)
  }

  if (!is.numeric(ncol) ||
      length(ncol) != 1 ||
      !is.finite(ncol) ||
      ncol < 1 ||
      !.tempssm_is_integerish(ncol)) {
    stop("`ncol` must be a positive integer.", call. = FALSE)
  }

  if (nrow * ncol < length(plots)) {
    stop("`nrow * ncol` must be at least the number of plots.", call. = FALSE)
  }

  grobs <- lapply(plots, ggplot2::ggplotGrob)

  mat <- matrix(grobs,
                nrow = nrow,
                ncol = ncol,
                byrow = TRUE)

  gtable::gtable_matrix(
    name = "layout",
    grobs = mat,
    widths  = grid::unit(rep(1, ncol), "null"),
    heights = grid::unit(rep(1, nrow), "null")
  )
}


#' Autoplot method for tempssm objects
#'
#' @description
#' Create diagnostic and component plots for a model fitted by
#' \code{tempssm()}. By default, all available components are plotted.
#'
#' @param object
#' An object returned by \code{tempssm()}.
#'
#' @param component
#' Character string specifying which component to plot.
#' One of \code{"level"}, \code{"drift"}, \code{"season"}, or \code{"ar1"}.
#' If NULL (default), all components are plotted.
#'
#' @inheritParams get_level_ts
#'
#' @param nrow,ncol Positive integers specifying the layout used when all
#'   components are plotted. The default is a 2 by 2 layout. These arguments
#'   are ignored when \code{component} is specified.
#'
#' @param ...
#' Additional arguments passed to the corresponding
#' \code{autoplot_*()} function.
#'
#' @return
#' A \code{ggplot} object if a single component is requested,
#' or a \code{gtable} object combining all component plots.
#'
#' @examples
#' \dontrun{
#' data(niigata_sst)
#' res <- tempssm(niigata_sst)
#'
#' # plot all components with 95% confidence interval
#' autoplot(res)
#'
#' # plot all components without 95% confidence interval
#' autoplot(res, ci = FALSE)
#'
#' # plot all components in one column
#' autoplot(res, nrow = 4, ncol = 1)
#'
#' # plot each of components
#' autoplot(res, component = "level", ci = FALSE)
#' }
#'
#' @method autoplot tempssm
#' @importFrom ggplot2 autoplot
#' @export
autoplot.tempssm <- function(object,
                             component = NULL,
                             ci = TRUE,
                             ci_level = 0.95,
                             nrow = 2,
                             ncol = 2,
                             ...) {

  plotters <- list(
    level  = autoplot_level,
    drift  = autoplot_drift,
    season = autoplot_season,
    ar1    = autoplot_ar1
  )

  if (!is.null(component)) {
    if (!is.character(component) || length(component) != 1) {
      stop("`component` must be a single character string.",
           call. = FALSE)
    }

    if (!component %in% names(plotters)) {
      stop(
        "`component` must be one of: ",
        toString(names(plotters)),
        call. = FALSE
      )
    }

    return(
      plotters[[component]](
        object,
        ci = ci,
        ci_level = ci_level,
        ...
      )
    )
  }

  plots <- lapply(
    plotters,
    function(f) f(object, ci = ci, ci_level = ci_level, ...)
  )

  g <- .make_gtable_layout(plots, nrow = nrow, ncol = ncol)

  grid::grid.newpage()
  grid::grid.draw(g)

  invisible(g)
}


#' Plot method for tempssm objects
#'
#' @description
#' Default base R plot method for objects fitted by \code{tempssm()}.
#' This method delegates to \code{autoplot.tempssm()} so that \code{plot(res)}
#' displays the same component plots as \code{autoplot(res)}.
#'
#' @param x An object returned by \code{tempssm()}.
#' @param ... Additional arguments passed to \code{autoplot.tempssm()}.
#'
#' @return
#' Invisibly returns the plotted \code{ggplot} object for a single component,
#' or the \code{gtable} object combining all component plots.
#'
#' @method plot tempssm
#' @export
#'
#' @examples
#' \dontrun{
#' data(niigata_sst)
#' res <- tempssm(niigata_sst)
#' plot(res)
#' plot(res, component = "level", ci = FALSE)
#' }
plot.tempssm <- function(x, ...) {
  p <- autoplot.tempssm(x, ...)

  if (inherits(p, "ggplot")) {
    print(p)
  }

  invisible(p)
}
